apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 2368 
  selector:
    app: ghost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1 
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
#            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 2368 

